// ------------------------------------------------------------------------------
//  <auto-generated>
//      這是由自動程式碼 UI 測試產生器產生的程式碼。
//      版本: 12.0.0.0
//
//      對這個檔案進行變更可能會導致不正確的行為，如果重新產生此程式碼，
//      將會造成檔案遺失。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodeUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;

    public class NewUIHtmlDocument : HtmlDocument
    {

        public NewUIHtmlDocument(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region 搜尋準則
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/SignFlow/SignFlowTemplate/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://172.16.2.90:82/SignFlow/SignFlowTemplate/Create";
            this.WindowTitles.Add("簽核流程範本管理-新增");
            #endregion
        }
    }
    
    [GeneratedCode("自動程式碼 UI 測試產生器", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - 使用 'RecordedMethod1Params' 將參數傳入這個方法。
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlEdit uI簽核流程名稱Edit = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UI簽核流程名稱Edit;
            HtmlEdit uI簽核流程範本管理新增Edit = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UI簽核流程範本管理新增Edit;
            HtmlDiv uI確定Pane = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UI確定Pane;
            HtmlHyperlink uIItemHyperlink = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UIS2id_ContentIDPane.UIItemHyperlink;
            HtmlDiv uI人員請假作業Pane = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UISelect2dropPane.UI人員請假作業Pane;
            HtmlDiv uI流程描述模式固定層級必簽層級Pane = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UISfttilePane.UI流程描述模式固定層級必簽層級Pane;
            HtmlRadioButton uIIsSetConditionRadioButton = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UIIsSetConditionRadioButton;
            HtmlDiv uI若要變更設定條件將刪除此範本目前所設定的Pane = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UI若要變更設定條件將刪除此範本目前所設定的Pane;
            HtmlButton uI確認Button = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UI確認Button;
            HtmlDiv uIItemPane = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UIItemPane;
            HtmlDiv uI簽核流程設定Pane = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document.UISfttilePane.UI簽核流程設定Pane;
            #endregion

            // 在 '簽核流程名稱' 文字方塊 中輸入 '請假Test'
            uI簽核流程名稱Edit.Text = this.RecordedMethod1Params.UI簽核流程名稱EditText;

            // 按一下 '簽核流程範本管理-新增' 文字方塊
            Mouse.Click(uI簽核流程範本管理新增Edit, new Point(231, 27));

            // 按一下 '確定' 窗格
            Mouse.Click(uI確定Pane, new Point(40, 18));

            // 按一下 連結
            Mouse.Click(uIItemHyperlink, new Point(97, 14));

            // 按一下 '人員請假作業' 窗格
            Mouse.Click(uI人員請假作業Pane, new Point(142, 16));

            // 設定旗標，以允許非必要動作失敗時 (例如，滑鼠停留動作失敗時) 能夠繼續播放。
            Playback.PlaybackSettings.ContinueOnError = true;

            // 滑鼠停留 '流程描述 模式 固定層級 必簽層級' 窗格 於 (1, 1)
            Mouse.Hover(uI流程描述模式固定層級必簽層級Pane, new Point(1, 1));

            // 重設旗標，以確保發生錯誤時播放會停止。
            Playback.PlaybackSettings.ContinueOnError = false;

            // 選取 'IsSetCondition' 選項按鈕
            uIIsSetConditionRadioButton.Selected = this.RecordedMethod1Params.UIIsSetConditionRadioButtonSelected;

            // 設定旗標，以允許非必要動作失敗時 (例如，滑鼠停留動作失敗時) 能夠繼續播放。
            Playback.PlaybackSettings.ContinueOnError = true;

            // 滑鼠停留 '× 若要變更設定條件，將刪除此範本目前所設定的簽核流程。 取消確認' 窗格 於 (1, 1)
            Mouse.Hover(uI若要變更設定條件將刪除此範本目前所設定的Pane, new Point(1, 1));

            // 重設旗標，以確保發生錯誤時播放會停止。
            Playback.PlaybackSettings.ContinueOnError = false;

            // 按一下 '確認' 按鈕
            Mouse.Click(uI確認Button, new Point(20, 10));

            // 設定旗標，以允許非必要動作失敗時 (例如，滑鼠停留動作失敗時) 能夠繼續播放。
            Playback.PlaybackSettings.ContinueOnError = true;

            // 滑鼠停留 '× 若要變更設定條件，將刪除此範本目前所設定的簽核流程。 取消確認' 窗格 於 (1, 1)
            Mouse.Hover(uI若要變更設定條件將刪除此範本目前所設定的Pane, new Point(1, 1));

            // 滑鼠停留  窗格 於 (1, 1)
            Mouse.Hover(uIItemPane, new Point(1, 1));

            // 重設旗標，以確保發生錯誤時播放會停止。
            Playback.PlaybackSettings.ContinueOnError = false;

            // 按一下 '簽核流程設定' 窗格
            Mouse.Click(uI簽核流程設定Pane, new Point(1306, 23));

            //客製程式
            //建立 HtmlDocument 物件，讓命名好看一點
            HtmlDocument UIBrowser = this.UI簽核流程範本管理新增InternetExWindow.UI簽核流程範本管理新增Document;

            //產生輸入框物件
            HtmlEdit InputGroupName = new HtmlEdit(UIBrowser);
            string CusDefInput = string.Format("{0}=\"{1}\"", "data-id", "group-desc");
            InputGroupName.SearchProperties.Add(new PropertyExpression(HtmlControl.PropertyNames.ControlDefinition, CusDefInput, PropertyExpressionOperator.Contains));
            InputGroupName.Text = "Hello";
            Playback.Wait(1000);

            //產生新增按鈕物件
            HtmlButton AddGroupBtn = new HtmlButton(UIBrowser);
            string CusDefButton = string.Format("{0}=\"{1}\"", "data-field", "btnAddGroupBox");
            AddGroupBtn.SearchProperties.Add(new PropertyExpression(HtmlControl.PropertyNames.ControlDefinition, CusDefButton, PropertyExpressionOperator.Contains));
            Mouse.Click(AddGroupBtn);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UI簽核流程範本管理新增InternetExWindow UI簽核流程範本管理新增InternetExWindow
        {
            get
            {
                if ((this.mUI簽核流程範本管理新增InternetExWindow == null))
                {
                    this.mUI簽核流程範本管理新增InternetExWindow = new UI簽核流程範本管理新增InternetExWindow();
                }
                return this.mUI簽核流程範本管理新增InternetExWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UI簽核流程範本管理新增InternetExWindow mUI簽核流程範本管理新增InternetExWindow;
        #endregion
    }
    
    /// <summary>
    /// 即將傳入 'RecordedMethod1' 的參數
    /// </summary>
    [GeneratedCode("自動程式碼 UI 測試產生器", "12.0.31101.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// 在 '簽核流程名稱' 文字方塊 中輸入 '請假Test'
        /// </summary>
        public string UI簽核流程名稱EditText = "請假Test";
        
        /// <summary>
        /// 選取 'IsSetCondition' 選項按鈕
        /// </summary>
        public bool UIIsSetConditionRadioButtonSelected = true;
        #endregion
    }
    
    [GeneratedCode("自動程式碼 UI 測試產生器", "12.0.31101.0")]
    public class UI簽核流程範本管理新增InternetExWindow : BrowserWindow
    {
        
        public UI簽核流程範本管理新增InternetExWindow()
        {
            #region 搜尋準則
            this.SearchProperties[UITestControl.PropertyNames.Name] = "簽核流程範本管理-新增";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("簽核流程範本管理-新增");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UI簽核流程範本管理新增Document UI簽核流程範本管理新增Document
        {
            get
            {
                if ((this.mUI簽核流程範本管理新增Document == null))
                {
                    this.mUI簽核流程範本管理新增Document = new UI簽核流程範本管理新增Document(this);
                }
                return this.mUI簽核流程範本管理新增Document;
            }
        }
        #endregion
        
        #region Fields
        private UI簽核流程範本管理新增Document mUI簽核流程範本管理新增Document;
        #endregion
    }
    
    [GeneratedCode("自動程式碼 UI 測試產生器", "12.0.31101.0")]
    public class UI簽核流程範本管理新增Document : HtmlDocument
    {
        
        public UI簽核流程範本管理新增Document(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜尋準則
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "簽核流程範本管理-新增";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/SignFlow/SignFlowTemplate/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://172.16.2.90:82/SignFlow/SignFlowTemplate/Create";
            this.WindowTitles.Add("簽核流程範本管理-新增");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UI簽核流程名稱Edit
        {
            get
            {
                if ((this.mUI簽核流程名稱Edit == null))
                {
                    this.mUI簽核流程名稱Edit = new HtmlEdit(this);
                    #region 搜尋準則
                    this.mUI簽核流程名稱Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "SignFlowName";
                    this.mUI簽核流程名稱Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "SignFlowName";
                    this.mUI簽核流程名稱Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "簽核流程名稱";
                    this.mUI簽核流程名稱Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUI簽核流程名稱Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUI簽核流程名稱Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUI簽核流程名稱Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"SignFlowName\" class=\"form-control\"";
                    this.mUI簽核流程名稱Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "11";
                    this.mUI簽核流程名稱Edit.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI簽核流程名稱Edit;
            }
        }
        
        public HtmlEdit UI簽核流程範本管理新增Edit
        {
            get
            {
                if ((this.mUI簽核流程範本管理新增Edit == null))
                {
                    this.mUI簽核流程範本管理新增Edit = new HtmlEdit(this);
                    #region 搜尋準則
                    this.mUI簽核流程範本管理新增Edit.SearchProperties[HtmlEdit.PropertyNames.Id] = "PeriodStartDate";
                    this.mUI簽核流程範本管理新增Edit.SearchProperties[HtmlEdit.PropertyNames.Name] = "PeriodStartDate";
                    this.mUI簽核流程範本管理新增Edit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "有效起始日";
                    this.mUI簽核流程範本管理新增Edit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUI簽核流程範本管理新增Edit.FilterProperties[HtmlEdit.PropertyNames.Title] = "簽核流程範本管理-新增";
                    this.mUI簽核流程範本管理新增Edit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUI簽核流程範本管理新增Edit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"PeriodStartDate\" title=\"簽核流程範本管理-新";
                    this.mUI簽核流程範本管理新增Edit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "12";
                    this.mUI簽核流程範本管理新增Edit.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI簽核流程範本管理新增Edit;
            }
        }
        
        public HtmlDiv UI確定Pane
        {
            get
            {
                if ((this.mUI確定Pane == null))
                {
                    this.mUI確定Pane = new HtmlDiv(this);
                    #region 搜尋準則
                    this.mUI確定Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUI確定Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUI確定Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "確定";
                    this.mUI確定Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUI確定Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "dwb2 dwb-e dwb";
                    this.mUI確定Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"0\" class=\"dwb2 dwb-e dwb\" role=\"button\"";
                    this.mUI確定Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "339";
                    this.mUI確定Pane.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI確定Pane;
            }
        }
        
        public UIS2id_ContentIDPane UIS2id_ContentIDPane
        {
            get
            {
                if ((this.mUIS2id_ContentIDPane == null))
                {
                    this.mUIS2id_ContentIDPane = new UIS2id_ContentIDPane(this);
                }
                return this.mUIS2id_ContentIDPane;
            }
        }
        
        public UISelect2dropPane UISelect2dropPane
        {
            get
            {
                if ((this.mUISelect2dropPane == null))
                {
                    this.mUISelect2dropPane = new UISelect2dropPane(this);
                }
                return this.mUISelect2dropPane;
            }
        }
        
        public UISfttilePane UISfttilePane
        {
            get
            {
                if ((this.mUISfttilePane == null))
                {
                    this.mUISfttilePane = new UISfttilePane(this);
                }
                return this.mUISfttilePane;
            }
        }
        
        public HtmlRadioButton UIIsSetConditionRadioButton
        {
            get
            {
                if ((this.mUIIsSetConditionRadioButton == null))
                {
                    this.mUIIsSetConditionRadioButton = new HtmlRadioButton(this);
                    #region 搜尋準則
                    this.mUIIsSetConditionRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Id] = "radioEnable";
                    this.mUIIsSetConditionRadioButton.SearchProperties[HtmlRadioButton.PropertyNames.Name] = "IsSetCondition";
                    this.mUIIsSetConditionRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Value] = "True";
                    this.mUIIsSetConditionRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.LabeledBy] = null;
                    this.mUIIsSetConditionRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Title] = null;
                    this.mUIIsSetConditionRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ItemCount] = "2";
                    this.mUIIsSetConditionRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.Class] = "ace";
                    this.mUIIsSetConditionRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.ControlDefinition] = "name=\"IsSetCondition\" class=\"ace\" id=\"ra";
                    this.mUIIsSetConditionRadioButton.FilterProperties[HtmlRadioButton.PropertyNames.TagInstance] = "15";
                    this.mUIIsSetConditionRadioButton.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUIIsSetConditionRadioButton;
            }
        }
        
        public HtmlDiv UI若要變更設定條件將刪除此範本目前所設定的Pane
        {
            get
            {
                if ((this.mUI若要變更設定條件將刪除此範本目前所設定的Pane == null))
                {
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane = new HtmlDiv(this);
                    #region 搜尋準則
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "×\r\n若要變更設定條件，將刪除此範本目前所設定的簽核流程。\r\n\r\n取消確認";
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "bootbox modal fade in";
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"-1\" class=\"bootbox modal fade in\" role=\"dialog\" aria-hidden=\"false\" sty" +
                        "le=\"display: block;\"";
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "207";
                    this.mUI若要變更設定條件將刪除此範本目前所設定的Pane.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI若要變更設定條件將刪除此範本目前所設定的Pane;
            }
        }
        
        public HtmlButton UI確認Button
        {
            get
            {
                if ((this.mUI確認Button == null))
                {
                    this.mUI確認Button = new HtmlButton(this);
                    #region 搜尋準則
                    this.mUI確認Button.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUI確認Button.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUI確認Button.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "確認";
                    this.mUI確認Button.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUI確認Button.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUI確認Button.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUI確認Button.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"button\" da";
                    this.mUI確認Button.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "31";
                    this.mUI確認Button.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI確認Button;
            }
        }
        
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region 搜尋準則
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "modal-backdrop fade";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"modal-backdrop fade\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "196";
                    this.mUIItemPane.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUI簽核流程名稱Edit;
        
        private HtmlEdit mUI簽核流程範本管理新增Edit;
        
        private HtmlDiv mUI確定Pane;
        
        private UIS2id_ContentIDPane mUIS2id_ContentIDPane;
        
        private UISelect2dropPane mUISelect2dropPane;
        
        private UISfttilePane mUISfttilePane;
        
        private HtmlRadioButton mUIIsSetConditionRadioButton;
        
        private HtmlDiv mUI若要變更設定條件將刪除此範本目前所設定的Pane;
        
        private HtmlButton mUI確認Button;
        
        private HtmlDiv mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("自動程式碼 UI 測試產生器", "12.0.31101.0")]
    public class UIS2id_ContentIDPane : HtmlDiv
    {
        
        public UIS2id_ContentIDPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜尋準則
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "s2id_ContentID";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "select2-container select2-allowclear select2";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"select2-container select2-allowclear select2\" id=\"s2id_ContentID\" style=\"w" +
                "idth: 100%;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "52";
            this.WindowTitles.Add("簽核流程範本管理-新增");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItemHyperlink
        {
            get
            {
                if ((this.mUIItemHyperlink == null))
                {
                    this.mUIItemHyperlink = new HtmlHyperlink(this);
                    #region 搜尋準則
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItemHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "\r\n ";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "void(0)";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:void(0)";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "select2-choice";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "tabindex=\"-1\" class=\"select2-choice\" onc";
                    this.mUIItemHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIItemHyperlink.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUIItemHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItemHyperlink;
        #endregion
    }
    
    [GeneratedCode("自動程式碼 UI 測試產生器", "12.0.31101.0")]
    public class UISelect2dropPane : HtmlDiv
    {
        
        public UISelect2dropPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜尋準則
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "select2-drop";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "人員加班申請作業\r\n\r\n\r\n人員排班作業\r\n\r\n\r\n人員請假作業\r\n\r\n\r\n休假";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "select2-drop select2-display-none select2-with-searchbox select2-drop-active";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"select2-drop select2-display-none select2-with-searchbox select2-drop-acti" +
                "ve\" id=\"select2-drop\" style=\"left: 496.54px; top: 333px; width: 687px; display: " +
                "block;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "205";
            this.WindowTitles.Add("簽核流程範本管理-新增");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UI人員請假作業Pane
        {
            get
            {
                if ((this.mUI人員請假作業Pane == null))
                {
                    this.mUI人員請假作業Pane = new HtmlDiv(this);
                    #region 搜尋準則
                    this.mUI人員請假作業Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUI人員請假作業Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUI人員請假作業Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "人員請假作業";
                    this.mUI人員請假作業Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUI人員請假作業Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "select2-result-label";
                    this.mUI人員請假作業Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"select2-result-label\"";
                    this.mUI人員請假作業Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "209";
                    this.mUI人員請假作業Pane.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI人員請假作業Pane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUI人員請假作業Pane;
        #endregion
    }
    
    [GeneratedCode("自動程式碼 UI 測試產生器", "12.0.31101.0")]
    public class UISfttilePane : HtmlDiv
    {
        
        public UISfttilePane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜尋準則
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "sft-tile";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "簽核流程設定  \r\n\r\n\r\n\r\n\r\n流程描述 \r\n\r\n\r\n\r\n模式 \r\n\r\n 固";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"sft-tile\" style=\"position: relative;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "59";
            this.WindowTitles.Add("簽核流程範本管理-新增");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UI流程描述模式固定層級必簽層級Pane
        {
            get
            {
                if ((this.mUI流程描述模式固定層級必簽層級Pane == null))
                {
                    this.mUI流程描述模式固定層級必簽層級Pane = new HtmlDiv(this);
                    #region 搜尋準則
                    this.mUI流程描述模式固定層級必簽層級Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUI流程描述模式固定層級必簽層級Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUI流程描述模式固定層級必簽層級Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "流程描述 \r\n\r\n\r\n\r\n模式 \r\n\r\n 固定層級  \r\n\r\n 必簽層級  \r\n";
                    this.mUI流程描述模式固定層級必簽層級Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUI流程描述模式固定層級必簽層級Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "widget-main";
                    this.mUI流程描述模式固定層級必簽層級Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"widget-main\"";
                    this.mUI流程描述模式固定層級必簽層級Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "61";
                    this.mUI流程描述模式固定層級必簽層級Pane.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI流程描述模式固定層級必簽層級Pane;
            }
        }
        
        public HtmlDiv UI簽核流程設定Pane
        {
            get
            {
                if ((this.mUI簽核流程設定Pane == null))
                {
                    this.mUI簽核流程設定Pane = new HtmlDiv(this);
                    #region 搜尋準則
                    this.mUI簽核流程設定Pane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUI簽核流程設定Pane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUI簽核流程設定Pane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "簽核流程設定  ";
                    this.mUI簽核流程設定Pane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUI簽核流程設定Pane.FilterProperties[HtmlDiv.PropertyNames.Class] = "widget-header";
                    this.mUI簽核流程設定Pane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"widget-header\"";
                    this.mUI簽核流程設定Pane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "59";
                    this.mUI簽核流程設定Pane.WindowTitles.Add("簽核流程範本管理-新增");
                    #endregion
                }
                return this.mUI簽核流程設定Pane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUI流程描述模式固定層級必簽層級Pane;
        
        private HtmlDiv mUI簽核流程設定Pane;
        #endregion
    }
}
